Venue.create(name: '1oak',city: 'New York', address: "453 west 17th street New York")
Venue.create(name: '42 West',city: 'New York', address: "220 West 42nd Street 12th Floor New York NY")
Venue.create(name: '49 Grove',city: 'New York', address: "49 GROVE ST(BTWN BLEECKER & GROVE ST) New York")
Venue.create(name: '809 NYC',city: 'New York', address: "809 Lounge 112 Dyckman Street New York, NY 10040 New York")
Venue.create(name: '9A West Harlem',city: 'New York', address: "2331 12th Avenue (133rd St) New York")
Venue.create(name: "Allure",city: 'New York', address: "33-02 Queens Boulevard Long Island City")
Venue.create(name: "Amazura",city: 'New York', address: "91-12 144th Pl Jamaica")
Venue.create(name: "Area Lounge",city: 'New York', address: "89-25 130th Street Richmond Hill Richmond Hill")
Venue.create(name: "Attic Rooftop & Lounge,city",city: 'New York', address: "251 West 48th Street New York")
Venue.create(name: "Ava Rooftop Lounge",city: 'New York', address: "210 West 55th Street New York")
Venue.create(name: "Avenue Beach Club",city: 'New York', address: "23 Ocean Ave Long Branch")
Venue.create(name: "Babys All Right",city: 'New York', address: "146 Broadway Brooklyn")
Venue.create(name: "Bamboo Lounge",city: 'New York', address: "Bamboo 985 Morris Ave Bronx, NY 10456 New York")
Venue.create(name: "Baroque NYC",city: 'New York', address: "19-44 Steinway Street Astoria")
Venue.create(name: "Brooklyn Terrace",city: 'New York', address: "216 Duffield St, Brooklyn, NY 11201 Brooklyn")
Venue.create(name: "Bungalo",city: 'New York', address: "32-03 Broadway Astoria")
Venue.create(name: "Buzz Night Club",city: 'New York', address: "103 empire blvd Brooklyn")
Venue.create(name: "Cantina Rooftop",city: 'New York', address: "605 W 48th St New York")
Venue.create(name: "Cappello",city: 'New York', address: "21 7th Ave New York")
Venue.create(name: "Cellar Bar",city: 'New York', address: "40 W. 40th Street New York")
Venue.create(name: "Chrystie 141",city: 'New York', address: "141 Chrystie St New York")
Venue.create(name: "Cielo",city: 'New York', address: "18 Little West 12th Street New York")
Venue.create(name: "Cliff Lounge",city: 'New York', address: "440 West 202nd St Manhattan, NY 10034 New York")
Venue.create(name: "Club Cache NYC",city: 'New York', address: "22 West 39th Street New York")
Venue.create(name: "Coco Bongo NYC",city: 'New York', address: "36-21 Steinway St Queens Long Island City")
Venue.create(name: "Coliseum Night Club",city: 'New York', address: "South Broadway White Plains New York")
Venue.create(name: "Copacapana",city: 'New York', address: "268 West 47th Street New York
")
Venue.create(name: "Copia NYC",city: 'New York', address: "307 East 53rd Street New York")
Venue.create(name: "DL Rooftop",city: 'New York', address: "95 Delancey Street New York")
Venue.create(name: "Empire Rooftop",city: 'New York', address: "44 West 63rd Street New York")
Venue.create(name: "Finale",city: 'New York', address: "199 Bowery‎ New York")
Venue.create(name: "Gansevoort Park Rooftop",city: 'New York', address: "420 PARK AVE SOUTH New York")
Venue.create(name: "Gilded Lily",city: 'New York', address: "408 W 15th St New York")
Venue.create(name: "Glazz",city: 'New York', address: "79-51 Albion Ave - off Queens Blvd New York")
Venue.create(name: "Highline Ballroom",city: 'New York', address: "431 West 16th Street New York")
Venue.create(name: "Hope Garage",city: 'New York', address: "163 Hope St Williamsburg")
Venue.create(name: "Hotel Chantelle",city: 'New York', address: "92 Ludlow St New York")
Venue.create(name: "Hudson Terrace",city: 'New York', address: "621 West 46th Street, New York")
Venue.create(name: "Katra",city: 'New York', address: "217 Bowery Street New York")
Venue.create(name: "Le Reve Lounge NYC",city: 'New York', address: "125 East 54th Street New York")
Venue.create(name: "Level R",city: 'New York', address: "44 West 63rd Street New York")
Venue.create(name: "Lexicon",city: 'New York', address: "226 East 54TH Street New York")
Venue.create(name: "Liberty Theater",city: 'New York', address: "233 W 41ST ST New York")
Venue.create(name: "Lit NYC",city: 'New York', address: "Lit, 93 2nd Ave, New York, NY 10001 New York")
Venue.create(name: "LUST NY",city: 'New York', address: "225 47th Street New York")
Venue.create(name: "Marquee NYC",city: 'New York', address: "289 10th Avenue New York")
Venue.create(name: "Milk River",city: 'New York', address: "960 Atlantic Avenue Brooklyn")
Venue.create(name: "Opus 51",city: 'New York', address: "51 Gansevoort ST New York")
Venue.create(name: "Output Night Club",city: 'New York', address: "74 Wythe Ave New York")
Venue.create(name: "Pacha NYC",city: 'New York', address: "618 W 46th St New York")
Venue.create(name: "Palladium",city: 'New York', address: "36-14 31st Street Astoria")
Venue.create(name: "Phuket Lounge",city: 'New York', address: "701 W 135th St New York")
Venue.create(name: "Plunge Gansevoort",city: 'New York', address: "18 Ninth Avenue New York")
Venue.create(name: "Public House",city: 'New York', address: "140 E. 41st St., New York, NY 10017 New York")
Venue.create(name: "RdV",city: 'New York', address: "409 West 13th Street New York")
Venue.create(name: "Rooftop 760",city: 'New York', address: "760 8th ave New York")
Venue.create(name: "Rosewood",city: 'New York', address: "5 E 19th St., Cnr of 5th Avenue Manhattan, New York New York")
Venue.create(name: "Sky Room",city: 'New York', address: "330 West 40th Street New York")
Venue.create(name: "Slate Lounge NYC",city: 'New York', address: "54 West 21st Street New York")
Venue.create(name: "Space",city: 'New York', address: "637 West 50th St New York")
Venue.create(name: "Stage 48",city: 'New York', address: "605 W.48th b/w 11th ave & 12th Ave New York")
Venue.create(name: "Stellan Nyc",city: 'New York', address: "2 West 35th Street, New York, NY")
Venue.create(name: "Studio 21",city: 'New York', address: "59 West 21st Street New York, NY New York")
Venue.create(name: "Studio 299",city: 'New York', address: "299 Vandervoort Ave. New York")
Venue.create(name: "Mission",city: 'New York', address: "16 W 36th St New York")
Venue.create(name: "Tagline",city: 'New York', address: "221 West 38th Street New York")
Venue.create(name: "Taj",city: 'New York', address: "48 West 21st Street New York")
Venue.create(name: "Tenjune",city: 'New York', address: "26 Little West 12th New York")
Venue.create(name: "The Bowery Electric",city: 'New York', address: "327 Bowery New York")
Venue.create(name: "The Leonora",city: 'New York', address: "525 W 29th St New York")
Venue.create(name: "The Varick Room",city: 'New York', address: "54 Varick Street New York")
Venue.create(name: "Toy",city: 'New York', address: "18 9th Ave New York")
Venue.create(name: "VIP Room",city: 'New York', address: "409 W 13th St, New York, New York")
Venue.create(name: "TAO Downtown",city: 'New York', address: "Maritime Hotel, 92 9th Ave, New York, NY 10011")
Venue.create(name: "The Raven",city: 'New York', address: "55 Gansevoort St, New York, NY 10014")
Venue.create(name: "Lavo",city: 'New York', address: "39 E 58th St, New York, NY 10022")
Venue.create(name: "Provocateur",city: 'New York', address: "Gansevoort Meatpacking NYC, 18 9th Ave, New York, NY 10014")
Venue.create(name: "Le Bain",city: 'New York', address: "848 Washington St, New York, NY 10014")
Venue.create(name: "Electric Room",city: 'New York', address: "355 W 16th St, New York, NY 10011")
Venue.create(name: "Up&Down",city: 'New York', address: "409 W 13th St, New York, New York")
Venue.create(name: "PH-D",city: 'New York', address: "355 W 16th St")
Venue.create(name: "The Griffin",city: 'New York', address: "50 Gansevoort St, New York, NY 10014")
Venue.create(name: "Avenue",city: 'New York', address: "116 10th Ave, New York, NY 10011")
Venue.create(name: "Gaslight",city: 'New York', address: "400 W 14th St, New York, NY 10014")
Venue.create(name: "No. 8",city: 'New York', address: "357 W 16th St, New York, NY 10011")
Venue.create(name: "W.i.P",city: 'New York', address: "34 Vandam St., downstairs, New York, NY 10013")
Venue.create(name: "Riff Raff",city: 'New York', address: "360 Park Ave S, New York, NY 10010")
Venue.create(name: "Fat Black Pussy Cat",city: 'New York', address: "130 W 3rd St, New York, NY 10012")
Venue.create(name: "Electric Room",city: 'New York', address: "355 W 16th St, New York, NY 10011")






Like.create(liker_id: 1, likee_id: 2, like: true)